package sifive.fpgashells.ip.xilinx.xdma

import chisel3._
import circt.stage.ChiselStage
import freechips.rocketchip.util.ElaborationArtefacts
import java.nio.charset.StandardCharsets
import java.nio.file.{Files, Paths}

/** Exact flat port declaration for the user's Vivado 2023.1 XDMA 4.1 rev.23 VEO.
  *
  * Fixed configuration: VCU118, DMA Endpoint, Gen2 x8, AXI-MM 256/64/4 bits,
  * one H2C and one C2H channel, AXI-Lite 32-bit user control, one user IRQ.
  * Regenerate and compare the VEO before changing this configuration.
  * Directions are relative to the AMD IP, including AXI ready/response inputs.
  */
class XDMAEndpointIO extends Bundle {

  // PCIe clocks, reset, lanes, and status
  val sys_clk             = Input(Clock())
  val sys_clk_gt          = Input(Clock())
  val sys_rst_n           = Input(Bool())
  val user_lnk_up         = Output(Bool())
  val pci_exp_txp         = Output(UInt(8.W))
  val pci_exp_txn         = Output(UInt(8.W))
  val pci_exp_rxp         = Input(UInt(8.W))
  val pci_exp_rxn         = Input(UInt(8.W))
  val axi_aclk            = Output(Clock())
  val axi_aresetn         = Output(Bool())
  val usr_irq_req         = Input(UInt(1.W))
  val usr_irq_ack         = Output(UInt(1.W))
  val msi_enable          = Output(Bool())
  val msi_vector_width    = Output(UInt(3.W))

  // AXI4 memory-mapped DMA master (256-bit data)
  val m_axi_awready       = Input(Bool())
  val m_axi_wready        = Input(Bool())
  val m_axi_bid           = Input(UInt(4.W))
  val m_axi_bresp         = Input(UInt(2.W))
  val m_axi_bvalid        = Input(Bool())
  val m_axi_arready       = Input(Bool())
  val m_axi_rid           = Input(UInt(4.W))
  val m_axi_rdata         = Input(UInt(256.W))
  val m_axi_rresp         = Input(UInt(2.W))
  val m_axi_rlast         = Input(Bool())
  val m_axi_rvalid        = Input(Bool())
  val m_axi_awid          = Output(UInt(4.W))
  val m_axi_awaddr        = Output(UInt(64.W))
  val m_axi_awlen         = Output(UInt(8.W))
  val m_axi_awsize        = Output(UInt(3.W))
  val m_axi_awburst       = Output(UInt(2.W))
  val m_axi_awprot        = Output(UInt(3.W))
  val m_axi_awvalid       = Output(Bool())
  val m_axi_awlock        = Output(Bool())
  val m_axi_awcache       = Output(UInt(4.W))
  val m_axi_wdata         = Output(UInt(256.W))
  val m_axi_wstrb         = Output(UInt(32.W))
  val m_axi_wlast         = Output(Bool())
  val m_axi_wvalid        = Output(Bool())
  val m_axi_bready        = Output(Bool())
  val m_axi_arid          = Output(UInt(4.W))
  val m_axi_araddr        = Output(UInt(64.W))
  val m_axi_arlen         = Output(UInt(8.W))
  val m_axi_arsize        = Output(UInt(3.W))
  val m_axi_arburst       = Output(UInt(2.W))
  val m_axi_arprot        = Output(UInt(3.W))
  val m_axi_arvalid       = Output(Bool())
  val m_axi_arlock        = Output(Bool())
  val m_axi_arcache       = Output(UInt(4.W))
  val m_axi_rready        = Output(Bool())

  // AXI4-Lite user-register master (32-bit data)
  val m_axil_awaddr       = Output(UInt(32.W))
  val m_axil_awprot       = Output(UInt(3.W))
  val m_axil_awvalid      = Output(Bool())
  val m_axil_awready      = Input(Bool())
  val m_axil_wdata        = Output(UInt(32.W))
  val m_axil_wstrb        = Output(UInt(4.W))
  val m_axil_wvalid       = Output(Bool())
  val m_axil_wready       = Input(Bool())
  val m_axil_bvalid       = Input(Bool())
  val m_axil_bresp        = Input(UInt(2.W))
  val m_axil_bready       = Output(Bool())
  val m_axil_araddr       = Output(UInt(32.W))
  val m_axil_arprot       = Output(UInt(3.W))
  val m_axil_arvalid      = Output(Bool())
  val m_axil_arready      = Input(Bool())
  val m_axil_rdata        = Input(UInt(32.W))
  val m_axil_rresp        = Input(UInt(2.W))
  val m_axil_rvalid       = Input(Bool())
  val m_axil_rready       = Output(Bool())
}

/** Instantiates the vendor IP; it does not implement a DMA engine in Chisel.
  *
  * Caller responsibilities: physical PCIe clock/reset/pins, proper AXI slaves,
  * clock-domain crossings and host control. Unused usr_irq_req may be tied low;
  * AXI ready/response inputs require real responders.
  */
class XDMAEndpointBlackBox extends BlackBox {
  override def desiredName: String = XDMAEndpointIP.moduleName
  val io = IO(new XDMAEndpointIO)

  // Preserve collateral from other IPs, and register this fixed IP only once.
  if (!ElaborationArtefacts.files.exists(_._1 == XDMAEndpointIP.artifactName)) {
    ElaborationArtefacts.add(XDMAEndpointIP.artifactName, XDMAEndpointIP.vivadoTcl)
  }
}

private[xdma] object XDMAEndpointIP {
  val moduleName = "xdma_vcu118_ep"
  val artifactName = s"$moduleName.vivado.tcl"

  // A plain Scala string intentionally preserves Vivado's $variable syntax.
  val vivadoTcl: String = """# Generated by XDMAEndpointBlackBox for the existing FPGA-shells IP flow.
# $ipdir is provided by fpga-shells/xilinx/common/tcl/prologue.tcl.
file mkdir $ipdir
create_ip -name xdma -vendor xilinx.com -library ip -version 4.1 \
    -module_name xdma_vcu118_ep -dir $ipdir -force
set xdma_ep_ip [get_ips xdma_vcu118_ep]

# Keep the two-stage ordering used by the successful standalone generation.
set xdma_ep_placement {
    CONFIG.functional_mode DMA
    CONFIG.mode_selection Advanced
    CONFIG.en_gt_selection true
    CONFIG.pcie_blk_locn X1Y2
    CONFIG.select_quad GTY_Quad_227
}
set_property -dict $xdma_ep_placement $xdma_ep_ip
if {![string match -nocase *Endpoint* [get_property CONFIG.device_port_type $xdma_ep_ip]]} {
    error "xdma_vcu118_ep must be an Endpoint"
}

set xdma_ep_requested {
    CONFIG.ref_clk_freq 100_MHz
    CONFIG.pl_link_cap_max_link_width X8
    CONFIG.pl_link_cap_max_link_speed 5.0_GT/s
    CONFIG.axi_data_width 256_bit
    CONFIG.axi_addr_width 64
    CONFIG.axi_id_width 4
    CONFIG.axisten_freq 125
    CONFIG.xdma_axi_intf_mm AXI_Memory_Mapped
    CONFIG.xdma_rnum_chnl 1
    CONFIG.xdma_wnum_chnl 1
    CONFIG.xdma_rnum_rids 8
    CONFIG.xdma_wnum_rids 8
    CONFIG.xdma_num_usr_irq 1
    CONFIG.axilite_master_en true
    CONFIG.axist_bypass_en false
    CONFIG.cfg_ext_if false
    CONFIG.cfg_mgmt_if false
    CONFIG.dma_reset_source_sel User_Reset
    CONFIG.drp_clk_sel Internal
    CONFIG.pf0_msi_enabled true
    CONFIG.pf0_msix_enabled false
}
set_property -dict $xdma_ep_requested $xdma_ep_ip

# Defaults observed in the actual Vivado 2023.1 VEO/configuration report.
# Check them so a differing catalog cannot silently change BlackBox ports.
set xdma_ep_expected_defaults {
    CONFIG.xdma_axilite_slave false
    CONFIG.xdma_dsc_bypass false
    CONFIG.xdma_sts_ports false
    CONFIG.axi_aclk_loopback false
    CONFIG.gtcom_in_core_usp 2
    CONFIG.gtwiz_in_core_usp 1
    CONFIG.axilite_master_scale Megabytes
    CONFIG.axilite_master_size 1
    CONFIG.vendor_id 10EE
    CONFIG.pf0_device_id 9028
    CONFIG.coreclk_freq 250
}
foreach {xdma_ep_key xdma_ep_wanted} [concat $xdma_ep_placement $xdma_ep_requested $xdma_ep_expected_defaults] {
    set xdma_ep_actual [get_property $xdma_ep_key $xdma_ep_ip]
    if {[string is boolean -strict $xdma_ep_wanted] && [string is boolean -strict $xdma_ep_actual]} {
        set xdma_ep_matches [expr {bool($xdma_ep_wanted) == bool($xdma_ep_actual)}]
    } else {
        set xdma_ep_matches [string equal -nocase $xdma_ep_wanted $xdma_ep_actual]
    }
    if {!$xdma_ep_matches} {
        error "xdma_vcu118_ep: $xdma_ep_key expected '$xdma_ep_wanted', got '$xdma_ep_actual'"
    }
}
# The parent FPGA-shells flow runs generate_target/export_ip_user_files.
# This fragment deliberately does not create a project or launch synthesis.
"""
}

/** Elaboration-only top: forwards all ports, including clock/reset ports.
  * This is not a usable FPGA top, behavioral DMA model, or board design.
  */
class XDMAEndpointSmokeTop extends RawModule {
  val io = IO(new XDMAEndpointIO)
  val endpoint = Module(new XDMAEndpointBlackBox)
  io <> endpoint.io
}

/** Run from the Chipyard root:
  * java -jar scripts/sbt-launch.jar \
  *   "fpga_shells/runMain sifive.fpgashells.ip.xilinx.xdma.XDMAEndpointSmoke /new/output"
  *
  * Emits CHIRRTL plus the registered IP Tcl without BOOM elaboration or Vivado.
  * emitCHIRRTL does not invoke the external firtool executable.
  */
object XDMAEndpointSmoke {
  def main(args: Array[String]): Unit = {
    require(args.length == 1, "Provide one NEW output directory")
    val out = Paths.get(args(0)).toAbsolutePath.normalize()
    require(!Files.exists(out), s"Output directory already exists: $out")
    Files.createDirectories(out)

    // Standalone stage invocation does not flush ElaborationArtefacts itself.
    // Restore prior state on exit so repeated runMain calls in sbt remain safe.
    val previousArtifacts = ElaborationArtefacts.files
    ElaborationArtefacts.files = Nil
    try {
      val chirrtl = ChiselStage.emitCHIRRTL(new XDMAEndpointSmokeTop)
      val generated = ElaborationArtefacts.files
        .filter(_._1 == XDMAEndpointIP.artifactName)
      require(generated.size == 1, "Expected exactly one XDMA IP Tcl artifact")
      val ipTcl = generated.head._2()

      Files.write(out.resolve("XDMAEndpointSmokeTop.fir"),
        chirrtl.getBytes(StandardCharsets.UTF_8))
      Files.write(out.resolve(XDMAEndpointIP.artifactName),
        ipTcl.getBytes(StandardCharsets.UTF_8))

      println("STEP2_OK: Chisel elaboration and IP Tcl emission completed")
      println(s"CHIRRTL: ${out.resolve("XDMAEndpointSmokeTop.fir")}")
      println(s"IP Tcl: ${out.resolve(XDMAEndpointIP.artifactName)}")
      println("No Vivado synthesis, board programming, or DMA functional test was run.")
    } finally {
      ElaborationArtefacts.files = previousArtifacts
    }
  }
}

